---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-virtualmachine-zespre-com-v1-kubebmc
  failurePolicy: Fail
  name: mkubebmc.kb.io
  rules:
  - apiGroups:
    - virtualmachine.zespre.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubebmcs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-virtualmachine-zespre-com-v1-kubebmc
  failurePolicy: Fail
  name: vkubebmc.kb.io
  rules:
  - apiGroups:
    - virtualmachine.zespre.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubebmcs
  sideEffects: None
